# action.yml
name: "Clusters: Delete from JSON file"
inputs:
  config-file:
    description: Path to the clusters JSON config data file
    required: true
  name:
    description: Name of the cluster
    required: true
runs:
  using: docker
  image: "docker://ghcr.io/pashmakguru/gha-platform-orchestrator:latest"
  args:
  - clusters:delete
  - --config-file
  - ${{ inputs.config-file }}
  - --name
  - ${{ inputs.name }}
