# action.yml
name: "Fronthub: Transform config"
inputs:
  input-file:
    description: Path to the fronthub JSON config data file
    required: true
  output-file:
    description: Path to the transformed module-prepared output to store
    required: true
runs:
  using: docker
  image: "docker://ghcr.io/pashmakguru/gha-platform-orchestrator:latest"
  args:
  - fronthub:transform
  - --input-file
  - ${{ inputs.input-file }}
  - --output-file
  - ${{ inputs.output-file }}

