# action.yml
name: "Fronthub: Transform config"
inputs:
  input-file:
    description: Path to the fronthub JSON config data file
    required: true
  output-file:
    description: Path to the transformed module-prepared output to store
    required: true
  port-client-id:
    description: Client ID to connect to Port
    required: true
  port-client-secret:
    description: Client secret to connect to Port
    required: true
runs:
  using: docker
  image: "docker://ghcr.io/pashmakguru/gha-platform-orchestrator:latest"
  args:
  - fronthub:transform
  - --input-file
  - ${{ inputs.input-file }}
  - --output-file
  - ${{ inputs.output-file }}
  - --port-client-id
  - ${{ inputs.port-client-id }}
  - --port-client-secret
  - ${{ inputs.port-client-secret }}
