# action.yml
name: "Fronthub: Delete DNS Zone from JSON file"
inputs:
  config-file:
    description: Path to the fronthub JSON config data file
    required: true
  domain:
    description: Name of the domain
    required: true
runs:
  using: docker
  image: "ghcr.io/pashmakguru/gha-platform-orchestrator:latest"
  args:
  - fronthub:delete-dns-zone
  - --config-file
  - ${{ inputs.config-file }}
  - --domain
  - ${{ inputs.domain }}

